import { useEffect, useMemo, useState } from 'react';
import { resolveApiBaseUrl } from '../config/api.js';
import { t } from '../i18n/i18n.js';
import type { CalendarEntry, SeasonName } from '../models/calendar.js';
import type { ContentItem } from '../models/content.js';
import { getSeasonCalendar, getWeeklyCalendar } from '../services/calendar.service.js';
import { ContentCard } from '../components/ContentCard.js';

const seasons:SeasonName[]=['winter','spring','summer','fall'];
const seasonKey={winter:'calendar.season.winter',spring:'calendar.season.spring',summer:'calendar.season.summer',fall:'calendar.season.fall'} as const;
export function CalendarPage(){const baseUrl=useMemo(()=>resolveApiBaseUrl(import.meta.env.VITE_API_BASE_URL,import.meta.env.PROD),[]);const [weekly,setWeekly]=useState<CalendarEntry[]>([]);const now=new Date();const [season,setSeason]=useState<SeasonName>(()=>{const m=now.getMonth()+1;return m<=2||m===12?'winter':m<=5?'spring':m<=8?'summer':'fall';});const [year,setYear]=useState(now.getFullYear());const [seasonItems,setSeasonItems]=useState<ContentItem[]>([]);useEffect(()=>{const c=new AbortController();void getWeeklyCalendar(baseUrl,undefined,c.signal).then((x)=>{if(!c.signal.aborted)setWeekly(x.items);}).catch(()=>{});return()=>c.abort();},[baseUrl]);useEffect(()=>{const c=new AbortController();void getSeasonCalendar(baseUrl,season,year,c.signal).then((x)=>{if(!c.signal.aborted)setSeasonItems(x.items);}).catch(()=>{});return()=>c.abort();},[baseUrl,season,year]);return <main className="v16-page v17-calendar"><header><p className="eyebrow">{t('calendar.nav')}</p><h1>{t('calendar.title')}</h1><p>{t('calendar.subtitle')}</p></header><section><h2>{t('calendar.week')}</h2>{weekly.length===0?<p className="v17-empty">{t('calendar.emptyWeek')}</p>:<div className="v17-calendar-list">{weekly.map((entry)=><article key={`${entry.content.id}-${entry.airingAt}`}><a href={`/contenido/${entry.content.id}`}><img src={entry.content.artwork} alt="" loading="lazy"/><span><strong>{entry.content.title}</strong><small>{new Date(entry.airingAt).toLocaleString()} {entry.episodeNumber?`· ${t('calendar.episode')} ${entry.episodeNumber}`:''}</small></span></a></article>)}</div>}</section><section><div className="v17-calendar-controls"><h2>{t('calendar.season')}</h2><select value={season} onChange={(e)=>setSeason(e.target.value as SeasonName)}>{seasons.map((value)=><option key={value} value={value}>{t(seasonKey[value])}</option>)}</select><input type="number" min="1900" max="2200" value={year} onChange={(e)=>setYear(Number(e.target.value))}/></div>{seasonItems.length===0?<p className="v17-empty">{t('calendar.emptySeason')}</p>:<div className="catalog-results__grid">{seasonItems.map((item)=><ContentCard item={item} key={item.id}/>)}</div>}</section></main>;}
